### ISSUE TITLE
2.4.x releases are missing from the repo

### ISSUE THREAD

**Issue by fhuberts** [bndtools/releases#1]
- To not depend on Cloudbees
- To allow downstream projects to (easily) build against previous releases

**Comment by fhuberts** [comment]
BTW Updating this repo is in the release procedure I wrote and is in the bndtools repo, see https://github.com/bndtools/bndtools/blob/master/bndtools.manual/developer/RELEASE_CHECKLIST.md

**Comment by bjhargrave** [comment]
We are putting releases in bintray now. See https://bintray.com/bnd/dist/dist/view and https://bintray.com/bndtools/bndtools/update/view

**Comment by fhuberts** [comment]
That is only bnd.
I need bndtools.

Please re-open

**Comment by fhuberts** [comment]
And besides, that makes you depend on bintray. Same problem

**Comment by bjhargrave** [comment]
> That is only bnd.
> I need bndtools.

Did you not see the link for bndtools?

**Comment by fhuberts** [comment]
I did now.
